# Generated by Django 2.1.3 on 2018-12-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='phone',
            field=models.CharField(max_length=16, verbose_name='Phone'),
        ),
    ]
